services:
  db:
    image: jeffrygonzalez/pg-thing:v2
    environment:
      PGDATA: /pgdata
    ports:
      - 5439:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DESIGN: dracula

